### ISSUE TITLE
Sockethub container exits with error

### ISSUE THREAD

**Issue by raucao** [67P/orchestration#2]
Just cloned the repos and ran `fig up`, but the Sockethub container doesn't come up successfully.

I can see this in the logs:

```
sockethub_1    | module.js:340
sockethub_1    |     throw err;
sockethub_1    |           ^
sockethub_1    | Error: Cannot find module 'consoleplusplus/console++'
sockethub_1    |     at Function.Module._resolveFilename (module.js:338:15)
sockethub_1    |     at Function.Module._load (module.js:280:25)
sockethub_1    |     at Module.require (module.js:364:17)
sockethub_1    |     at require (module.js:380:17)
sockethub_1    |     at Object.<anonymous> (/sockethub/lib/sockethub/sockethub.js:24:1)
```

FYI: Sockethub comes up without this error, when running `npm install` and Redis directly on my system.

**Comment by raucao** [comment]
We probably need to update the container to use node.js 0.12?

**Comment by silverbucket** [comment]
`console++` is a dep of Sockethub `v0.x`, not the new code, so this bug can be closed.

**Comment by raucao** [comment]
![rejoicing](https://cloud.githubusercontent.com/assets/842/7651801/dbcb4258-fb04-11e4-8b52-e169ae0b69e3.gif)
