### ISSUE TITLE
Node.js deployment

### ISSUE THREAD

**Issue by raucao** [67P/orchestration#3]
https://medium.com/@mikemaccana/how-i-deploy-node-apps-on-linux-2014-edition-309d606219ca

We should probably upgrade the Hetzner box to 15.04 as soon as possible and use systemd from the start. Everything else is basically legacy already.

We need node.js deployment for Sockethub, hal8000 and possibly other programs soon.

**Comment by raucao** [comment]
This is informative, too: https://stackoverflow.com/questions/4681067/how-to-run-a-node-js-application-as-its-own-process/28542093#28542093

Not sure about the Git setup yet. I like the idea of tagging master as green from Travis and fetching the tag on the server. (Similar to what we already do at @5apps, but with tags instead of branches.)

**Comment by gregkare** [comment]
There's a chef repo on gitlab for this, closing this one
